dist: trusty
addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache: yarn
before_install:
  # starting a GUI to run tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - npm run coverage
